dnl
dnl $Id: check-multiprocessing.m4,v 1.5 2003/11/27 14:36:23 ralf Exp $
dnl

AC_DEFUN([RTEMS_CHECK_MULTIPROCESSING],
[dnl
AC_REQUIRE([RTEMS_ENV_RTEMSCPU])dnl
AC_REQUIRE([RTEMS_ENABLE_MULTIPROCESSING])dnl
])
