#
#  $Id: Makefile.dir,v 1.4 2000/06/12 15:00:14 joel Exp $
#

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc

include $(RTEMS_CUSTOM)
include $(RTEMS_ROOT)/make/directory.cfg

SUBDIRS=a b c your-directories-go-here

